### ISSUE TITLE
namespace collision with before blocks

### ISSUE THREAD

**Issue by blackfist** [sinatra/sinatra-contrib#181] opened 2015-12-05 05:09 UTC
It appears that before blocks inside a namespace will run even when requests are made against a different namespace if the two namespaces start with the same characters.

## steps to reproduce

1. Run this file
```
require 'sinatra'
require 'sinatra/namespace'

before {warn "The root before block is running as expected"}

namespace "/api" do
  before { warn "The /api before block is running"}
  get {"You're awesome"}
end

namespace "/apikeys" do
  before { warn "The /apikeys before block is running"}
  get {"You're awesome"}
end

namespace "/frank" do
  before { warn "The /frank before block is running"}
  get {"You're awesome"}
end
```

2. Make these requests
```
curl http://localhost:4567/api
curl http://localhost:4567/apikeys
curl http://localhost:4567/frank
```

3. Observe the output in the running sinatra process
```
Listening on localhost:4567, CTRL+C to stop
The root before block is running as expected
The /api before block is running
127.0.0.1 - - [04/Dec/2015:23:03:26 -0600] "GET /api HTTP/1.1" 200 14 0.0045
The root before block is running as expected
The /api before block is running
The /apikeys before block is running
127.0.0.1 - - [04/Dec/2015:23:03:30 -0600] "GET /apikeys HTTP/1.1" 200 14 0.0007
The root before block is running as expected
The /frank before block is running
127.0.0.1 - - [04/Dec/2015:23:03:36 -0600] "GET /frank HTTP/1.1" 200 14 0.0013
```

As you can see, when a `GET` was sent to `/apikeys` both the `api` and the `apikeys` before block ran, but that was not the case for the request to `/frank`.

**Comment by stjhimy** [comment] 2015-12-07 10:58
I was able to replicate it here https://github.com/stjhimy/sinatra-contrib/commit/e460157d718892e5eee7c10b18ca9ce03fc9f458 but not able to fix yet. 

The fix is probably around here https://github.com/sinatra/sinatra-contrib/blob/master/lib/sinatra/namespace.rb#L264 if someone is wondering.

**Comment by zzak** [comment] 2016-05-24 07:46
@stjhimy The problem is this is testing the stdout which could be printed in a different order than the blocks are actually fired.

This gets even more complicated if the web-server is handling the requests concurrently.

**Comment by zzak** [comment] 2016-07-20 07:17
I'd think we should close this, it's too hard to test reliably and `$stdout` isn't very helpful here unfortunately IMO.

**Closed by zzak** 2016-07-20 07:17 UTC
