### ISSUE TITLE
yield_content not keeping original encoding?

### ISSUE THREAD

**Issue by wielgosm** [sinatra/sinatra-contrib#68] opened 2012-10-08 00:07 UTC
Hi,

I am using content_for in my application. In one of my documents I am using the following character in one of my erb files: '×'.

I have the following declarations in my app:

```ruby
    Encoding.default_external = Encoding::UTF_8
    Encoding.default_internal = Encoding::UTF_8
```

All my documents are utf-8. My locale is the following:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Using erb to output stuff seems to be working ok, for example (just for hand-debugging):
```ruby
<% content_for :messages_and_contents do |file| %>
  <%=erb :'parts/messages'%>
  <%p erb(:'parts/messages').encoding.to_s%>
  <%=erb file%>
  <%p erb(file).encoding.to_s%>
<% end %>
```
Both output strings to the console give me UTF-8.

Using yield_content seems to break things. For example:
```ruby
yield_content(:messages_and_contents,file)
```

...The output string for yield_content is US-ASCII.

Is something wrong on my side or is yield_content at fault here?

**Comment by zzak** [comment] 2015-05-23 00:11
Closing as a duplicate of #75

**Closed by zzak** 2015-05-23 00:11 UTC
Labels: content-for
